# Generated by Django 4.1.2 on 2022-10-21 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('tagtype', models.CharField(choices=[('female', 'Female Tag'), ('male', 'Male Tag'), ('tag', 'No Gender Tag'), ('artist', 'Artist'), ('series', 'Series'), ('character', 'Character'), ('language', 'Language')], max_length=10)),
            ],
        ),
    ]
