# Generated by Django 4.1.3 on 2022-11-15 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_tag_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='gallery_count',
            field=models.IntegerField(default=-1),
        ),
    ]
