# Generated by Django 4.1.3 on 2022-11-16 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_tag_gallery_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorites',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('gallery_id', models.BigIntegerField()),
                ('user_id', models.IntegerField()),
            ],
        ),
    ]
